In [17]:
import numpy as np
import mindspore
import mindspore.ops as ops
from mindspore.ops.operations.nn_ops import PSROIPooling
from d2l import mindspore as d2l

X = ops.arange(16, dtype=mindspore.float32).reshape(1, 1, 4, 4)
X

Tensor(shape=[1, 1, 4, 4], dtype=Float32, value=
[[[[ 0.00000000e+00,  1.00000000e+00,  2.00000000e+00,  3.00000000e+00],
   [ 4.00000000e+00,  5.00000000e+00,  6.00000000e+00,  7.00000000e+00],
   [ 8.00000000e+00,  9.00000000e+00,  1.00000000e+01,  1.10000000e+01],
   [ 1.20000000e+01,  1.30000000e+01,  1.40000000e+01,  1.50000000e+01]]]])

In [18]:
rois = mindspore.Tensor([[0, 0, 2, 2], [0, 1, 3, 3]], dtype=mindspore.float32)

In [20]:
roi_pooling = d2l.RoiPooling(mode='th', pool_size=(2,2))
roi_pooling.get_pooled_rois(X, rois)

0 1 0 1
[[[0. 1.]
  [4. 5.]]]
0 1 1 2
[[[1. 2.]
  [5. 6.]]]
1 2 0 1
[[[4. 5.]
  [8. 9.]]]
1 2 1 2
[[[ 5.  6.]
  [ 9. 10.]]]
0 1 0 1
[[[4. 5.]
  [8. 9.]]]
0 1 2 3
[[[ 6.  7.]
  [10. 11.]]]
1 2 0 1
[[[ 8.  9.]
  [12. 13.]]]
1 2 2 3
[[[10. 11.]
  [14. 15.]]]


array([[[[ 5.,  6.],
         [ 9., 10.]]],


       [[[ 9., 11.],
         [13., 15.]]]])